name: filterapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  deepar_flutter: ^0.0.5
  get: ^4.6.6
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  image_gallery_saver: ^2.0.3
  video_player: ^2.9.2
  intl: ^0.20.1
  video_thumbnail: ^0.5.3
  share_plus: ^10.1.3
  chewie: ^1.8.7
  on_audio_query: ^2.9.0 
  better_player: ^0.0.83
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/filters/
    - assets/previews/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500    
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700       
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100


    - family: Altoysitalicpersonalonly
      fonts:
        - asset: assets/fonts/Altoysitalicpersonalonly.ttf

    - family: DINNextLTPro
      fonts:
        - asset: assets/fonts/DINNextLTPro-Medium.ttf
          weight: 500

